name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: f01&#45;01&#45;01
      id: f01-45-01-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: f01&#45;01&#45;01
        setup-command: make -s compile
        command: make -s test_01
        input: |
          student-add#12S21001#Dhino Turnip#S1 Sistem Informasi
          student-add#21S21001#Samuel Purba#S1 Manajemen Rekayasa
          student-add#12S21002#Marudut Tampubolon#S1 Sistem Informasi
          student-show-all
          ---
        expected-output: |
          12S21001|Dhino Turnip|S1 Sistem Informasi
          12S21002|Marudut Tampubolon|S1 Sistem Informasi
          21S21001|Samuel Purba|S1 Manajemen Rekayasa
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: f01&#45;02&#45;01
      id: f01-45-02-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: f01&#45;02&#45;01
        setup-command: make -s compile
        command: make -s test_01
        input: |
          student-add#12S21001#Dhino Turnip#S1 Sistem Informasi
          student-add#21S21001#Samuel Purba#S1 Manajemen Rekayasa
          student-add#12S21002#Marudut Tampubolon#S1 Sistem Informasi
          student-show-all
          course-add#10S2201#Aljabar Linier#4#3
          course-add#10S2202#Jaringan Komputer#4#3
          course-add#10S2203#Sistem Operasi#4#3
          course-add#12S2201#Analisis dan Desain Sistem#4#3
          course-add#12S2202#Interaksi Manusia-Komputer#4#3
          course-add#12S2203#Pemrograman Berorientasi Objek#4#3
          course-add#KUS3001#Analisis Dampak Lingkungan#6#2
          course-add#10S1002#Pemrograman Prosedural#2#2
          course-show-all
          ---
        expected-output: |
          12S21001|Dhino Turnip|S1 Sistem Informasi
          12S21002|Marudut Tampubolon|S1 Sistem Informasi
          21S21001|Samuel Purba|S1 Manajemen Rekayasa
          10S1002|Pemrograman Prosedural|2|2
          10S2201|Aljabar Linier|4|3
          10S2202|Jaringan Komputer|4|3
          10S2203|Sistem Operasi|4|3
          12S2201|Analisis dan Desain Sistem|4|3
          12S2202|Interaksi Manusia-Komputer|4|3
          12S2203|Pemrograman Berorientasi Objek|4|3
          KUS3001|Analisis Dampak Lingkungan|6|2
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: f01&#45;02&#45;02
      id: f01-45-02-45-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: f01&#45;02&#45;02
        setup-command: make -s compile
        command: make -s test_01
        input: |
          student-add#12S21001#Dhino Turnip#S1 Sistem Informasi
          student-add#21S21001#Samuel Purba#S1 Manajemen Rekayasa
          student-add#12S21002#Marudut Tampubolon#S1 Sistem Informasi
          student-add#12S21002#Marwudut Tampubolon#S1 Sistem Informasi
          student-show-all
          course-add#10S2201#Aljabar Linier#4#3
          course-add#10S2202#Jaringan Komputer#4#3
          course-add#10S2203#Sistem Operasi#4#3
          course-add#12S2201#Analisis dan Desain Sistem#4#3
          course-add#12S2202#Interaksi Manusia-Komputer#4#3
          course-add#12S2203#Pemrograman Berorientasi Objek#4#3
          course-add#KUS3001#Analisis Dampak Lingkungan#6#2
          course-add#10S1002#Pemrograman Prosedural#2#2
          course-add#10S1002#Pemrograman Prosedural#2#2
          course-show-all
          ---
        expected-output: |
          12S21001|Dhino Turnip|S1 Sistem Informasi
          12S21002|Marudut Tampubolon|S1 Sistem Informasi
          21S21001|Samuel Purba|S1 Manajemen Rekayasa
          10S1002|Pemrograman Prosedural|2|2
          10S2201|Aljabar Linier|4|3
          10S2202|Jaringan Komputer|4|3
          10S2203|Sistem Operasi|4|3
          12S2201|Analisis dan Desain Sistem|4|3
          12S2202|Interaksi Manusia-Komputer|4|3
          12S2203|Pemrograman Berorientasi Objek|4|3
          KUS3001|Analisis Dampak Lingkungan|6|2
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: f01&#45;03&#45;01
      id: f01-45-03-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: f01&#45;03&#45;01
        setup-command: make -s compile
        command: make -s test_01
        input: |
          student-add#12S21001#Dhino Turnip#S1 Sistem Informasi
          student-add#21S21001#Samuel Purba#S1 Manajemen Rekayasa
          student-add#12S21002#Marudut Tampubolon#S1 Sistem Informasi
          course-add#KUS3001#Analisis Dampak Lingkungan#6#2
          course-add#10S2201#Aljabar Linier#4#3
          course-add#10S2202#Jaringan Komputer#4#3
          course-add#10S2203#Sistem Operasi#4#3
          course-add#12S2201#Analisis dan Desain Sistem#4#3
          course-add#12S2202#Interaksi Manusia-Komputer#4#3
          course-add#12S2203#Pemrograman Berorientasi Objek#4#3
          course-add#10S1002#Pemrograman Prosedural#2#2
          enroll#12S21001#KUS3001
          enroll#12S21001#10S2201
          enroll#12S21001#10S2202
          enroll#12S21001#10S2203
          enroll#12S21001#12S2201
          enroll#12S21001#12S2202
          enroll#12S21001#12S2203
          enroll#12S21002#10S1002
          enroll#12S21002#10S2201
          enroll#12S21002#10S2202
          enroll#12S21002#10S2203
          enroll#12S21002#12S2201
          enroll#12S21002#12S2202
          enroll#12S21002#12S2203
          student-show#12S21001
          student-show#12S21002
          ---
        expected-output: |
          12S21001|Dhino Turnip|S1 Sistem Informasi
          10S2201|Aljabar Linier|4|3
          10S2202|Jaringan Komputer|4|3
          10S2203|Sistem Operasi|4|3
          12S2201|Analisis dan Desain Sistem|4|3
          12S2202|Interaksi Manusia-Komputer|4|3
          12S2203|Pemrograman Berorientasi Objek|4|3
          KUS3001|Analisis Dampak Lingkungan|6|2
          12S21002|Marudut Tampubolon|S1 Sistem Informasi
          10S1002|Pemrograman Prosedural|2|2
          10S2201|Aljabar Linier|4|3
          10S2202|Jaringan Komputer|4|3
          10S2203|Sistem Operasi|4|3
          12S2201|Analisis dan Desain Sistem|4|3
          12S2202|Interaksi Manusia-Komputer|4|3
          12S2203|Pemrograman Berorientasi Objek|4|3
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: f01&#45;03&#45;02
      id: f01-45-03-45-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: f01&#45;03&#45;02
        setup-command: make -s compile
        command: make -s test_01
        input: |
          student-add#12S21001#Dhino Turnip#S1 Sistem Informasi
          student-add#21S21001#Samuel Purba#S1 Manajemen Rekayasa
          student-add#12S21002#Marudut Tampubolon#S1 Sistem Informasi
          student-add#21S21099#Samwel Purba#S1 Manajemen Rekayasa
          course-add#KUS3001#Analisis Dampak Lingkungan#6#2
          course-add#10S2201#Aljabar Linier#4#3
          course-add#10S2202#Jaringan Komputer#4#3
          course-add#10S2203#Sistem Operasi#4#3
          course-add#12S2201#Analisis dan Desain Sistem#4#3
          course-add#12S2202#Interaksi Manusia-Komputer#4#3
          course-add#12S2201#Analisis dan Desain Sistem#4#3
          course-add#12S2203#Pemrograman Berorientasi Objek#4#3
          course-add#10S1002#Pemrograman Prosedural#2#2
          enroll#12S21001#KUS3001
          enroll#12S21001#10S2201
          enroll#12S21001#10S2202
          enroll#12S21001#10S2203
          enroll#12S21001#12S2201
          enroll#12S21001#12S2202
          enroll#12S21001#12S2203
          enroll#12S21002#10S1002
          enroll#12S21002#10S2201
          enroll#12S21002#10S2202
          enroll#12S21002#10S2203
          enroll#12S21002#12S2201
          enroll#12S21002#12S2202
          enroll#12S21002#12S2203
          student-show#12S21001
          course-show-all
          student-show#12S21002
          student-show-all
          ---
        expected-output: |
          12S21001|Dhino Turnip|S1 Sistem Informasi
          10S2201|Aljabar Linier|4|3
          10S2202|Jaringan Komputer|4|3
          10S2203|Sistem Operasi|4|3
          12S2201|Analisis dan Desain Sistem|4|3
          12S2202|Interaksi Manusia-Komputer|4|3
          12S2203|Pemrograman Berorientasi Objek|4|3
          KUS3001|Analisis Dampak Lingkungan|6|2
          10S1002|Pemrograman Prosedural|2|2
          10S2201|Aljabar Linier|4|3
          10S2202|Jaringan Komputer|4|3
          10S2203|Sistem Operasi|4|3
          12S2201|Analisis dan Desain Sistem|4|3
          12S2202|Interaksi Manusia-Komputer|4|3
          12S2203|Pemrograman Berorientasi Objek|4|3
          KUS3001|Analisis Dampak Lingkungan|6|2
          12S21002|Marudut Tampubolon|S1 Sistem Informasi
          10S1002|Pemrograman Prosedural|2|2
          10S2201|Aljabar Linier|4|3
          10S2202|Jaringan Komputer|4|3
          10S2203|Sistem Operasi|4|3
          12S2201|Analisis dan Desain Sistem|4|3
          12S2202|Interaksi Manusia-Komputer|4|3
          12S2203|Pemrograman Berorientasi Objek|4|3
          12S21001|Dhino Turnip|S1 Sistem Informasi
          12S21002|Marudut Tampubolon|S1 Sistem Informasi
          21S21001|Samuel Purba|S1 Manajemen Rekayasa
          21S21099|Samwel Purba|S1 Manajemen Rekayasa
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        F01-45-01-45-01_RESULTS: "${{steps.f01-45-01-45-01.outputs.result}}"
        F01-45-02-45-01_RESULTS: "${{steps.f01-45-02-45-01.outputs.result}}"
        F01-45-02-45-02_RESULTS: "${{steps.f01-45-02-45-02.outputs.result}}"
        F01-45-03-45-01_RESULTS: "${{steps.f01-45-03-45-01.outputs.result}}"
        F01-45-03-45-02_RESULTS: "${{steps.f01-45-03-45-02.outputs.result}}"
      with:
        runners: f01-45-01-45-01,f01-45-02-45-01,f01-45-02-45-02,f01-45-03-45-01,f01-45-03-45-02
